### ISSUE TITLE
Update count when filtering in search tabs

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1006]
**Description**:
After a search, the results table is not updating the count of results when filtering columns.

Steps to test:
1. go to search and search for 'battery'
2. in the investigation tab (with 239 results), filter by title to include 'structure'
3. it is clear that the results chage, but the count (239) is not updated.

This should be fix for filtering in each of the tabs.

<img width="1826" alt="Screenshot 2021-12-14 at 11 29 50" src="https://user-images.githubusercontent.com/1417033/145990220-2252324b-45dc-4751-a179-2044c2a853ad.png">

**Acceptance criteria**:
- [x] Update count of results in each search tab after filtering.

**Comment by louise-davies** [comment]
also - there's no progress/loading bar

**Comment by AkhilMag13** [comment]
Finished implementing the functionality in 539b490
![image](https://user-images.githubusercontent.com/88283659/146780238-f0184597-4d70-46f2-8bf5-dd1a0c5d0a04.png)
The other tabs are showing 0 because of issue #1008 - So must check if the results are being updated, when that issue is being resolved.

**Comment by AkhilMag13** [comment]
The progress bar works fine on Dataset and Datafile tabs but seems to run for a longer time when using the filters in Investigation - could be due to more columns

https://user-images.githubusercontent.com/88283659/146788379-c6c90eb1-a7eb-48c8-a72c-3e3f37d652cc.mp4


https://user-images.githubusercontent.com/88283659/146788350-83a0a246-fc86-43d8-b1a6-4c07dc700c04.mp4
