### ISSUE TITLE
Role selector and clear filters button on different lines

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#1126]
**Description**:
On the my data view, the role selector and the clear filters button are on different lines. They should be on the same line to look better styling wise

**Acceptance criteria**:
- [ ] My data view has role selector and clear filters button on same line

**Comment by joshuadkitenge** [comment]
The role selector and clear filters were aligned fine on the Chrome, but on the further inspection it was found that there was a misalignment on firefox #1128. From my investigation, I found that the misalignment was due to the CSS overflow property in the SELECT (Mui). Changing the value of this property from 'hidden' to 'clip' solves this problem (e93068b).
