### ISSUE TITLE
Unexpected sidebar behaviour on login page

### ISSUE THREAD

**Issue by mattjSTFC** [ral-facilities/datagateway#1265]
**Description**:
When a login error there is an unexpected transiton of the side bar navigation and menu button 

https://user-images.githubusercontent.com/56403718/170274520-d7f8ca8e-153c-4b40-9799-f803cf943570.mp4

**Acceptance criteria**:
- [ ] Sidebar should remain open or closed depending on user choice

**Comment by VKTB** [comment]
Thought I would add that I noticed this same behaviour when signing out.

**Comment by sam-glendenning** [comment]
I'm guessing this is because an action is firing to close the sidebar and then another immediately after to correct the last one or balance it out but either way it's not intentional. I'll investigate

**Comment by sam-glendenning** [comment]
Hi @mattjSTFC I just looked into this and remembered that this has been fixed in https://github.com/ral-facilities/scigateway/pull/1044. The fix has not been deployed to either ISIS site yet but has been deployed to both DLS prod and preprod (where you can generally find the most recent build).

You're welcome to double check you don't see this issue on DLS prod or preprod in case I'm overlooking a bug but as far as I'm concerned this issue has been addressed :)
