### ISSUE TITLE
Minor spelling mistake in help page

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1268]
**Description**:
Reported by Chris, there is a minor spelling mistake in the DLS help page, in the [Globus section](https://datagateway.diamond.ac.uk/help#globus-help), where it reads 'transfered' instead of 'transferred'

**Acceptance criteria**:
- [ ] Fix spelling mistake in help page

**Comment by sam-glendenning** [comment]
@louise-davies I looked into this and I couldn't figure out when you made this change because what's been deployed doesn't match what's on Gitlab. I presume it's not up to date with any "hotfixes" you may have made. So all that's needed here is that when you go to fix this issue and re-deploy, make sure what you commit to Gitlab omits the spelling error and then this can be closed.

**Comment by louise-davies** [comment]
@sam-glendenning I had committed the changes but forgot to push them! Sorry about that - I've fixed it and pushed the changes to ansible & fixed it on DLS prod.
