### ISSUE TITLE
Dates not ordered correctly

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#1306]
**Description**:
When checking the Admin download page in the ISIS instance, it seems that the dates are not ordered correctly (see screenshot).

To reproduce, 1. go to the Admin download page, 2. Filter full name by excluding 'Nagios', 3. Order the requested date in descending order.

<img width="285" alt="Screenshot 2022-07-04 at 09 24 05" src="https://user-images.githubusercontent.com/1417033/177114306-43d85d5d-8a34-4de5-aaf1-742a0bf0884e.png">

**Acceptance criteria**:
- [ ] Investigate and fix date ordering in Admin interface (and elsewhere?)

**Comment by louise-davies** [comment]
@agbeltran I picked this up and fixed it in https://github.com/ral-facilities/datagateway/pull/1250. This was released in `v1.1.0` whereas ISIS is currently on `v1.0.0`. (i.e. you can verify that this is fixed by trying it on DLS). When we do the TopCAT upgrade I'll upgrade the version of DG for ISIS
