### ISSUE TITLE
Investigated whether Patrick's search changes branch can be updated to develop

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#1361]
**Description**:
Patrick made changes to datagateway-search for his Lucene improvements stuff on his own branch, but this is now many commits behind develop and so would need to be made up to date. We should try and merge develop in and resolve merge conflicts, but if this is too complex (probably due to MUIv5 changes) - then we'll have to port all the changes over from his branch onto develop.

**Acceptance criteria**:
- [ ] Investigate whether we can merge develop into Patrick's branch

**Comment by kennethnym** [comment]
I have attempted to merge `develop` into the branch. This is the list of files that have conflicts:

![Screenshot 2022-07-29 114226](https://user-images.githubusercontent.com/19359984/181743144-7d1a4474-c49e-4888-8585-14947d083ad1.png)

(I think roughly 40 files are affected)

Although some of them are just snapshot conflicts and some of them are relatively easy to merge, a lot of test files are affected. On top of that, the branch is still on yarn v1. Since we need to migrate the affected test files to `testing-library` anyway, I don't think it is worth the effort to merge the complicated diffs. I think it will be easier to `cherry-pick` or port the changes to `develop` on a new branch. We can also consider rebasing the commits on the latest commits on `develop`.
