### ISSUE TITLE
Fix dataset text search

### ISSUE THREAD

**Issue by tswinb** [ral-facilities/datagateway#177]
Text search in `datagateway-search` in the dataset is not returning expected results. 
Some examples: search '105' or 'DATASET 105' and receive 'DATASET 422'. Search '422' or 'DATASET 422' and receive no results.

Acceptance criteria:

- [ ] Searching for text in the Dataset tab returns relevant results.

**Comment by louise-davies** [comment]
This is the same issue as icatproject/topcat#345 - this can technically be solved by using wildcards `*` around your search term - but this is onerous on users. This is likely related to how Lucene performs it's searches and thus relies on the Lucene/Elasticsearch changes in the ICAT project.

**Comment by agbeltran** [comment]
cc @stuartpullinger

**Comment by stuartpullinger** [comment]
I think this might be caused by the database and Lucene index being out of sync. I think that the database has been changed/updated since the Lucene index was created. Queries to Lucene only returns the IDs of the matches so I think it is returning an out of date ID. The indexing only happens when an entity is first created (using[ this method](https://github.com/icatproject/icat.server/blob/master/src/main/java/org/icatproject/core/entity/Dataset.java#L185)) or when prompted to do so by an [api call](https://repo.icatproject.org/site/icat/server/4.9.1/miredot/index.html#1268799821). Maybe try pinging the API (need to have a sessionId of a user in rootUserNames) with a `minid` of 0?

**Comment by louise-davies** [comment]
This is no longer an issue - searching `442` correctly locates `DATASET 442`, searching `105` brings up multiple results but that will be due to lucene behaviour, searching `DATASET 442` has the problem of including everything due to the word "DATASET" matching everything, so the term `"DATASET 442"` is required to search, but again I think this is the same behaviour as TopCAT
