### ISSUE TITLE
Customisable homepage?

### ISSUE THREAD

**Issue by kevinphippsstfc** [ral-facilities/datagateway#431]
**Description**:
I like the visual impact of the SciGateway homepage, although I'm a bit concerned that the Explore, Analyse, Record might be setting expectations a bit high at this stage - this is more of a long term goal I think.

Is the page customisable for each facility? As a minimum, for example, can we put the Diamond/ISIS logo on it and some words saying "Welcome to the Diamond/ISIS data archive".

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by agbeltran** [comment]
Thanks @kevinphippsstfc - this is a great point and something we should consider. The current homepage was only a temporary example and something we do need to improve considering the options you proposed. 

There is an issue on SciGateway about this, as we need to consider the interaction between the parent app and plugins. Current discussion is having the homepage configured by a URL pointing to the specific page (potentially from a plugin). See https://github.com/ral-facilities/scigateway/issues/427

**Comment by agbeltran** [comment]
DataGateway homepage should describe the functionality provided as follows (originally https://github.com/ral-facilities/scigateway/issues/427#issuecomment-815826281):

Replace the page
![image](https://user-images.githubusercontent.com/1417033/114066953-2b104380-9894-11eb-95f1-4115e950e394.png)


by adding the DG logo and the following text:
- Explore: Browse, explore and visualise the experimental data produced at the facility
- Discovery: Search for the experimental data according to different criteria
- Download: Retrieve the experimental data using a variety of download methods.

For now, remove the text "transforming... our national facilities.

We will discuss specific changes, and addition of logos, with each of the facilities, so we need to design it so that we may have different static home pages per facilty.
