### ISSUE TITLE
Switching tabs doesn't switch data type in search

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#479]
**Description**:
When you switch tabs in datagateway-search, it doesn't always switch the data to what should be displayed in  the table (i.e. switching from investigation to datasets still shows the investigations in the datasets table).

I noticed this in the demos, so to recreate: first search for just investigations, then tick datasets and research, then switch tabs. These steps might not be necessary for replicating the bug, but it happened in both demos with the same steps so should be a fairly stable bug replication method.

**Acceptance criteria**:
- [ ] Switching between entity type tabs correctly switches the data displayed

**Comment by patrick-austin** [comment]
Can't replicate the bug locally; switching tabs displays datasets as expected. Maybe I'm not following the steps correctly?

<img width="960" alt="search investigations" src="https://user-images.githubusercontent.com/61705287/101476055-0f784900-3945-11eb-94ad-47a685bb5b12.png">
<img width="960" alt="re-search investigations and datasets" src="https://user-images.githubusercontent.com/61705287/101476277-6b42d200-3945-11eb-8090-fa0fadf429d1.png">
<img width="960" alt="switch tabs" src="https://user-images.githubusercontent.com/61705287/101476287-6f6eef80-3945-11eb-90a5-fa7530743542.png">

**Comment by patrick-austin** [comment]
Have managed to replicate this. When the bug occurs (it wasn't consistent for me, and I could only trigger it when serving the plugin) `data` and `allIds` are being set by requests for both the currently viewed tab's entity, and the initially set tab for the view (investigations). This results in investigation data being dispalyed.

Removing the [automatic tab selection](https://github.com/ral-facilities/datagateway/blob/master/packages/datagateway-search/src/searchPageTable.tsx#L78) and setting the initial value to `'none'` rather than `'investigation'` seemed to work, but obviously this isn't ideal. 

When it does occur, the correct data can be fetched by applying sorting to the table.

My current fix was to map the value of the current tab to the state, with the intent to then pass this to the methods that request the data to make sure we only send them on the right tab. But just implementing the mapping without any checks in the tables themselves _seems_ to have fixed it (though as I couldn't reliably trigger the bug, I could have just been lucky and not triggered it while testing myself). It seems to be sensitive to the timing of the requests/tab switching.
