### ISSUE TITLE
[datagateway-table] Create breadcrumbs component

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#51]
Currently there's no way of navigating back to the parent entities of the current table. TopCAT has a "breadcrumb" component that displays the parent entities in a "folder" like structure

i.e. for ISIS:

(on datasets table)
[ISIS]() / [ALF]() / [cycle_18_1]() / CAL_ALF_YIG crystal test ESS / Dataset

for DIAMOND:
(on datafiles table)
[DIAMOND]() / [In House for Software - Mark Basham]() / [NT5977-1]() / topdir / Datafile

The component could be generated purely via `RouteComponentProps`, however we wouldn't have the entity names. Therefore I think we'll need to store the "current selected hierarchy" (display name and link url?) in the Redux state which is modified upon user navigation.

Acceptance criteria:
- [x] Breadcrumb component allows users to navigate up the entity hierarchy from their currently selected entity

**Comment by GoelBiju** [comment]
A draft pull request for the breadcrumbs component has been created #70 .

**Comment by GoelBiju** [comment]
Currently finishing of styling the breadcrumb:

- [ ] CSS styling; fix MaterialLink (Material UI Link Component) and Typography element wrapped styling,
- [ ] Tooltip disable on breadcrumbs which do not exceed the maximum width.

**Comment by GoelBiju** [comment]
Final to-do:

- [ ] Clean-up code for components in the breadcrumbs.componet file,
- [ ] Remove any debugging console logs within the code.

**Comment by GoelBiju** [comment]
A new issue is that cypress hangs in headless mode, which could possibly be [this issue](https://github.com/cypress-io/cypress/issues/5475) as pointed out by @louise-davies . We may have to rollback cypress to 3.4 or test out running it with the "--browser chrome" argument.

**Comment by agbeltran** [comment]
Linking to original user story: https://github.com/ral-facilities/datagateway-userstories/issues/46

**Comment by GoelBiju** [comment]
After the breadcrumbs code review meeting, there were several new issues opened and fixes to be made for this branch. These are specifically:

- [ ] Internationalisation; this is specific to the fact that we string format an 's' but this is only for English. When the application is translated to another language this is no longer feasible. Libraries such as [i18next](https://www.i18next.com/) or [Polyglot.js](https://airbnb.io/polyglot.js/) should be considered,

- [ ] Configuration file should be used instead of hardcoding specific conditions for DLS/ISIS i.e. using TITLE/VISIT_ID on encountering proposals in the path etc.

- [ ] Customise the breadcrumb trail to make it stand out on the screen; pointy breadcrumbs UI (CSS), base entity may have an icon (home icon?), background colour/varying shades on each breadcrumb,

- [ ] Move the ArrowToolip and any generic code to a separate re-usable file,

- [ ] Correct names in the code i.e. BreadcrumbState to PageBreadcrumbsState
 
- [ ] Remove 'N/A' and replace with empty string,

- [ ] Promises simplified in typing.

**Comment by GoelBiju** [comment]
The cypress issue has now been fixed for this branch and #82 will be closed when this branch is merged in.

**Comment by GoelBiju** [comment]
In addition, @louise-davies mentioned creating an array of the accepted entity names within [app.types](https://github.com/ral-facilities/datagateway/blob/master/packages/datagateway-common/src/app.types.tsx#L146) (based off the Entity type) in datagateway-common.

**Comment by GoelBiju** [comment]
With regards to internationalisation, #84 , it is best to have it for the whole application and not just individual components. For now, this will be omitted but there are comments within the breadcrumbs component which indicate where to include internationalisation i.e. where plurals are relevant (adding 's' to entity names).

**Comment by GoelBiju** [comment]
I have added a working chevron styled breadcrumbs to the code. This is mainly adapted from this [CodePen demo](https://codepen.io/Paulie-D/pen/WvjyNM). @louise-davies has created a [CodeSandbox demo] but it in order for this to implemented I need to change the prop/return types passed in/out to createStyles/withStyles. 

For the ease of making a working breadcrumb I have separated all the css to it's own individual [style.module.css](https://github.com/ral-facilities/datagateway/blob/feature/breadcrumbs-component-%2351/packages/datagateway-table/src/style.module.css) file.

**Comment by GoelBiju** [comment]
Some improvements for the future:

- [ ] Disbale the hover/active and green select colour for elements in the breadcrumb trail which do not have a link (e.g. icon and last entity),
- [ ] Display facility name alongside icon (pass in facilityName as a prop from the state to the PageBreadcrumbs componenet and render it).
