### ISSUE TITLE
Fix My Data e2e tests

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#659]
**Description**:
Currently, the myData tests fetch data for an anonymous user - which by definition doesn't make sense. This is currently fine on master due to a workaround, but this workaround is being removed as part of the switch to python-icat and so shouldn't be relied upon. The tests should login as a user which has data they are the user for - either we can do this by adding credential login back to that test, modifying the fake data + fake data generator script or via hacking the local storage token and manually changing the username.

**Acceptance criteria**:
- [ ] My Data table e2e tests run as a user that has data associated with it

**Comment by sam-glendenning** [comment]
I just had a go at this for feasibility's sake. Modifying the generator script or stubbing response data from the API could be tricky on a test-by-test basis, especially when it comes to testing filters and sorting. Since those work by querying the API, each response would have to be stubbed just to make the test pass and that seems to defeat the spirit of a true e2e test. I think we would need to have some sort of permanent user with data linked to it that we login as while running these tests. But open to ideas

**Comment by MRichards99** [comment]
I know Louise had some ideas about this but I don't know enough about them to give you guidance on what to do :(
