### ISSUE TITLE
Remove description column from facility cycle table

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#741]
**Description**:
This is always the same value in the ISIS database, so this is kind of redundant.

**Acceptance criteria**:
- [x] This column is no longer present

**Comment by GoelBiju** [comment]
@louise-davies does this also need to be removed from the ISIS facility cycle card view as well or should it stay the same?

**Comment by GoelBiju** [comment]
There is currently an issue with the resizing column e2e test for [`facilityCycles`](https://github.com/ral-facilities/datagateway/blob/master/packages/datagateway-dataview/cypress/integration/table/isis/facilityCycles.spec.ts#L33) where the width for the columns are not calculated correctly. I am currently trying to see what the fix for this is since the width for the scroll bar is not taken into account and the total width is just returned as `1000px`.
