### ISSUE TITLE
Reduce Tab Presses on Card View Sorting Options

### ISSUE THREAD

**Issue by MRichards99** [ral-facilities/datagateway#763]
**Description**:
While tabbing through card view, I noticed that navigating through the sort options required two presses of the tab key to get to the next one:
![image](https://user-images.githubusercontent.com/32678030/126634615-079320e8-abc3-42f7-853f-c6292a379e26.png)

This isn't a _major_ thing because a user can still sort the data - I wondered if there's a technical reason (ascending and descending maybe?) why this happens?

Opened this issue as a result of #738 

**Acceptance criteria**:
- [x] One tab press should get the user to the next sort field option

**Comment by GoelBiju** [comment]
@MRichards99 it seems the reason it requires two tab presses is that there are two buttons from the `ListItem` and the `TableSortLabel`. The `onClick` handler is on the `ListItem` so the first tab press followed by an enter works, whereas two tab presses and an enter does not since it focuses on the `TableSortLabel` which is the ascending/descending label. 

It is possible to set the `tabindex` to `-1` on the `TableSortLabel` which prevents the second tab focus and it looks like the quickest fix to this issue. I am looking into if it is possible there are other ways to prevent the `TableSortLabel` from being focused on.

**Comment by GoelBiju** [comment]
> @MRichards99 it seems the reason it requires two tab presses is due to the [`ListItem`](https://github.com/ral-facilities/datagateway/blob/master/packages/datagateway-common/src/card/cardView.component.tsx#L574) and the [`TableSortLabel`](https://github.com/ral-facilities/datagateway/blob/master/packages/datagateway-common/src/card/cardView.component.tsx#L592) elements used to form the sort options (in the `CardView` component) which both had their roles set to button. The `onClick` handler is on the `ListItem` so the first tab press followed by an enter works, whereas two tab presses and an enter press does not since it focuses on the `TableSortLabel` which is the ascending/descending label.
> 
> It is possible to set the `tabindex` to `-1` on the `TableSortLabel` which prevents the second tab focus and it looks like the quickest fix to this issue. I am looking into if it is possible there are other ways to prevent the `TableSortLabel` from being focused on.

As a follow-up, `TableSortLabel` uses `ButtonBase` so we cannot remove the button from it. `ListItem` has a `button` prop but disabling means the focus when hovering will not be present but you can still click the option. The best option maybe just to set the `tabindex` on the `TableSortLabel` to `-1`.
