### ISSUE TITLE
Search filters/table exceeds width of plugin container

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/datagateway#778]
**Description**:

Due to centering the search filters and search table in `datagateway-search` they exceed the width of the actual container in which the plugin loads when the sidebar is opened. This might be due to us setting the width of the filters/table by specifying the viewport width. We need to ensure the filters to not just move to the left to keep the same width but instead resize when the sidebar is opened on datagateway-search.

![image](https://user-images.githubusercontent.com/16869075/127365831-06f8300d-fe95-4859-90d5-ace5d2e979be.png)

**Acceptance criteria**:

- [x] Search filters and search table do not exceed the width of the plugin container.

**Comment by sam-glendenning** [comment]
It's interesting because this doesn't seem to affect the tables in dataview, regardless of window size, zoom, etc. It just always manages to compress to hold all elements on the screen and not require any horizontal or vertical scrolling. But the same logic does not apply to the tables in search for some reason. Why this is, I'm not sure at this point.

My working theory is it might have something to do with the fact that the tables themselves inherit this resize ability just fine but it breaks when you add them into a parent element which doesn't share this functionality. So perhaps it could be going wrong [here](https://github.com/ral-facilities/datagateway/blob/a4161e68215da251b3c0d63616d5e359120c9fdb/packages/datagateway-search/src/searchPageTable.tsx#L126) where the tables are being constructed. Perhaps the `AppBar` component with the `Tab` elements doesn't allow for this to happen

**Comment by GoelBiju** [comment]
@sam-glendenning has fixed this with https://github.com/ral-facilities/datagateway/pull/774/commits/426c08ff5984884485904b20aebe2b3578b2f20b. The solution was to ensure the the `Grid` component in which the search page table is held in is a `container` and not an `item`. This ensures it resizes accordinly rather than being fixed. 

Now the only time in which the both the search filters and search page table exceed the plugin container width is when the browser width is resized to being smaller than the `minWidth` defined for both the `Paper` components in which they are held in. This is fine since this is not very noticable.
