### ISSUE TITLE
Upgrade to React 17

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/datagateway#830]
**Description**:

At present in DataGateway we are using React 16.13.1. With the release of React 17, it would be ideal to upgrade to the newer version. The official [blog post](https://reactjs.org/blog/2020/10/20/react-v17.html) highlights the benefits of upgrading.

The only issue preventing an upgrade at the moment is there not being an official Enzyme adapter for React 17. There is an issue on the Enzyme repository (https://github.com/enzymejs/enzyme/issues/2429) which is currently in progress. This upgrade would have to wait until that is officially created.

I have created a matching issue in SciGateway for upgrading to React 17 (https://github.com/ral-facilities/scigateway/issues/768). Both will need to be upgraded at the same time.

**Acceptance criteria**:

- [ ] Upgrade DataGateway to React 17 (upgrade react and react-dom, check other packages too),
- [ ] Ensure types for React is up to date,
- [ ] Enzyme Adapter is updated for React 17.

**Comment by GoelBiju** [comment]
@louise-davies There is an [unofficial](https://github.com/wojtekmaj/enzyme-adapter-react-17) Enzyme adapter but we would need to look at whether it works fine with TypeScript (?).

**Comment by louise-davies** [comment]
I think what we need to do is to:
- [ ] Do upgrade to React 17 (react & react-dom), including type declarations
  - [ ] Fix anything broken due to React 17 upgrade
- [ ] Use unofficial Enzyme 17 adapter for now
  - [ ] Check that tests pass at this point
- [ ]  Future: evaluate whether it's worth switching over to testing-library/react. Many libraries are switching/have switched (including Material UI and that means to upgrade to Material UI 5 would be harder as we use their enzyme utils) and it seems to be "reacting" (pun intended) to React version updates an a more graceful way - which will help with future React updates. We can slowly move tests over component at a time as a "background" task (or e.g. next time someone works on some code, try to migrate the tests for that code)

**Comment by joelvdavies** [comment]
Here are some problems that need fixing after the upgrade:
- [ ]  Search page does not initially display results until tab is switched (seems set_current_tab action is never called initially)
