### ISSUE TITLE
Embargoed study landing pages can't read information from investigations

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#835]
**Description**:
This is most likely an issue to do ICAT rules more than anything else, but this is a blocker on decommissioning the old DOI landing pages.

**Acceptance criteria**:
- [ ] Embargoed/unreleased studies display all relevant info on their landing pages

**Comment by louise-davies** [comment]
@stuartpullinger highlighting this issue - is this something that can be changed in such a way to not affect the integrity of keeping data closed? i.e. a public step between study and investigation perhaps? As this functionality already exists on the DOI landing pages (i.e. embargoed investigations have their metadata displayed on study landing pages)

**Comment by agbeltran** [comment]
We discussed with @louise-davies that this will be sorted once we have ```DataPublication``` added to the ICAT schema, but it would be good to have an interim solution.

**Comment by MRichards99** [comment]
@louise-davies I've spent much of this afternoon trying to find a solution for this. I've been looking at the current query but trying to find a way to solve the missing investigations. I've been experimenting with some of the JPQL specific operators (`SIZE`, `IS EMPTY` etc.) but ultimately, because the investigation entity isn't a collection (not like `studyInvestigations` where they're presented as arrays since it's a one-to-many relationship) none of them work. 

Upon realising the above doesn't work, I've been trying to think about how to take your `/investigations` query further to remove the duplicates. Sadly ICAT Server doesn't support SELECT on multiple attributes which removes the simple solution of putting using a distinct filter on each of the fields we need. I've tried hacking where filters looking for `null` or `""` but that doesn't seem have materialised.

I think I've spent enough time on this to understand the problem so it might be time for a meeting to discuss further. The only other thought I had was to create another ISIS specific endpoint for this purpose but I'm not sure how it would work as I can't even find a solution in JPQL. Perhaps a seed for you to think about.
