### ISSUE TITLE
Issue navigating datasets

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#850]
**Description**:
These are the steps to reproduce:
1. navigate to https://datagateway.isis.stfc.ac.uk/browse/instrument/1/facilityCycle/2/investigation/24090528?view=card
2. click on 'view datasets' and get the card pointing to the raw data (see screenshot)
3. click on 'raw' and a page with datasets details (but empty) appears
4. then need to click on 'view datafiles' to go to the list of files

should the views in 2 and 3 above have been the same? should the view in 3 have more metadata about the dataset?

This navigation needs to be improved IMO.

<img width="1404" alt="Screenshot 2021-10-07 at 16 48 07" src="https://user-images.githubusercontent.com/1417033/136419942-3ce218c2-c5ce-490c-86a7-5d6de7d047a8.png">

<img width="1422" alt="Screenshot 2021-10-07 at 16 51 00" src="https://user-images.githubusercontent.com/1417033/136419962-7a9b303c-d8b8-43c6-aaf2-d957b141f15a.png">

cc @louise-davies 

**Acceptance criteria**:
- [ ] TBD

**Comment by MRichards99** [comment]
**Short answer**
Not a solution, but I think this issue is caused by inconsistencies in ISIS' ICAT data and this is a rare bug based on where we get dataset IDs from and how we use them. 

**Longer ramble written while investigating the issue**

Looking in the requests of dev tools, it is assumed that the investigation ID will be the same as the dataset ID? I make this implication because the ID of the investigation included in the `/findone` request is the same ID used in the `/datasets` request. I've looked at another example on DataGateway to ensure this is the case.

Screenshot 3 will be blank because there's no data to put onto the page (i.e. the `/datasets` response is an empty list. The thing that does surprise me is the location heading still appears despite no data, while the others do not.

When clicking on 'view datafiles', dataset ID 24089467 is used (the correct one). In screenshot 3, ID 24090528 is used (got from `/findone`). I'm slightly confused at why different places use different IDs, but I think that's just me not having the time to look into the code.

Perhaps we need to review where the IDs originally come from and how they are used in subsequent requests. Just needs someone looking at devtools alongside the code alongside Postman to check have a peer around ISIS ICAT. I'm happy to do this, but it might not be feasible to wait until I can investigate further (14th/15th I reckon). That being said, this could be something that Louise could answer for us in a few minutes based on her knowledge. 

It might be worth looking into why location doesn't disappear when the field is null in ICAT too.

Looking at the `/findone` and `/datasets` requests of an example that does work, I'm not sure if there's anything else that links an ISIS investigation to an ISIS dataset. For reference, I used https://datagateway.isis.stfc.ac.uk/browse/instrument/1/facilityCycle/1/investigation/24089694/dataset/24089230?view=card
