### ISSUE TITLE
Change "Cart" to "Selection" in default language files

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#858]
**Description**:
As agreed with ISIS, the name Cart needs to be replaced by Selection

**Acceptance criteria**:
- [ ] Change Cart to Selection across the site

**Comment by agbeltran** [comment]
Hi all, I'm reopening this issue because the text has been change to 'Selections' in plural rather than 'Selection' in singular. I think we have a single 'Selection' so this should be fixed to singular. Unless you discussed something else that makes it better to be in plural? Thanks cc @joelvdavies @louise-davies

**Comment by agbeltran** [comment]
I note that we have Selections and Downloads - but selection is the set of investigations/datasets/datafiles that have been selected at a particular point in time, while downloads are the historical downloads

**Comment by joelvdavies** [comment]
@agbeltran I agree just changing it now.

**Comment by louise-davies** [comment]
`datagateway-dataview`'s `default.json` still says `selections` and not `selection`

**Comment by joelvdavies** [comment]
Will fix the remaining ones in https://github.com/ral-facilities/datagateway/pull/991.
