### ISSUE TITLE
datagateway-download needs a settings file

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#88]
Currently there is no setting file which means there is no way of supplying things like URLs and facility names other than hardcoded. Currently, datagateway-download doesn't use Redux (and I don't think it will ever have to), so a config object will be needed and perhaps we can use [React Context API](https://reactjs.org/docs/context.html) to supply it to child components.

Acceptance criteria:
- [x] datagateway-download has a settings file that can be loaded and used to configure the plugin

**Comment by GoelBiju** [comment]
@louise-davies this can be worked on once #48 has been completed. Edited your issue to add in a link to the React Context API for explanation on its usage.

**Comment by GoelBiju** [comment]
@louise-davies would it be worth adding an `accessMethods` array or object to the `datagateway-download-settings` file?

**Comment by louise-davies** [comment]
Yes, it's where it needs to be defined. See https://github.com/icatproject/topcat/blob/master/yo/app/config/topcat.json.example#L594 to see that this is where TopCAT defines it. It also defines an IDS url per download type, which is definitely used by diamond (globus downloads are handled by a separate IDS).

**Comment by GoelBiju** [comment]
- [ ] Add in support for access methods in `datagateway-download-settings.json` and accept custom idsUrl for submitting and making downloads,

- [ ] Replace all the remaining hardcoded settings,

- [ ] Add in unit tests for ConfigProvider.

**Comment by GoelBiju** [comment]
Tests have been updated to reflect the addition of the `datagateway-download-settings.json` in https://github.com/ral-facilities/datagateway/commit/ff6355e1dbb2df62208fe838b282a8ce588a7caa. The `ConfigProvider` tests still need to be added and there are currently warnings stating due to not wrapping the `DownloadConfirmDialog` with the `ConfigProvider` as the settings are not passed on. The tests work fine without it however the console warnings persist, if we wrapped the `DownloadConfirmDialog` with the `ConfigProvider` the [`setProps`](https://github.com/ral-facilities/datagateway/blob/master/packages/datagateway-download/src/downloadConfirmation/downloadConfirmDialog.component.test.tsx#L328) call would fail as it is not the root component.

**Comment by GoelBiju** [comment]
All remaining unit tests for ConfigProvider have been added in https://github.com/ral-facilities/datagateway/commit/e47a8d3dd73def09d5a93d587cad4bca1006e14c.

**Comment by GoelBiju** [comment]
A solution still needs to be found for the [setProps problem](https://github.com/ral-facilities/datagateway/issues/88#issuecomment-586399342) and this branch will need master to include download status to have been merged in, so that download status will make use of the ConfigProvider.

**Comment by GoelBiju** [comment]
A fix for the issue regarding setProps and altering the props for a non-root component has been mentioned in the [enzyme repository](https://github.com/airbnb/enzyme/issues/1925#issuecomment-445490387). 

I have added the fix into the unit test which would throw warnings if the `DownloadSettingsContext` was not used and made use of the children property to alter the `open` prop for `DownloadConfirmDialog` so that it will close in the unit test.

**Comment by GoelBiju** [comment]
This issue now requires #104 to be merged into master in order to apply the settings changes to the download status table.

Also one small addition to make to the code is to apply the [`square`](https://material-ui.com/api/paper/#props) prop for the `Paper` component (which disables rounded corners) where appropriate. An example would be to the results component above the table and to the Paper component holding the tables in place in `datagateway-table` and `datagateway-download` packages. This change will be easier once the download status branch has been merged in.

- [ ] Apply the `square` prop for `Paper` components appropriately.

**Comment by GoelBiju** [comment]
> Items remaining for this issue include:
> 
> * [x]  Add in support for access methods in `datagateway-download-settings.json` and accept custom idsUrl for submitting and making downloads (**blocked** until the download status table branch to has been merged in),
> * [x]  Replace all the remaining hardcoded settings,
> * [x]  Add in unit tests for ConfigProvider and update all unit tests which failing to include a mocked `datagateway-download-settings.json` request.

The download status branch (#104 ) has been merged into master and the datagateway settings changes have been added to the `DownloadStatusTable` as well in https://github.com/ral-facilities/datagateway/commit/156559d3870a0dac7c73626cd72cee3966cd288d.
