### ISSUE TITLE
Repeated titles in details panels in card views

### ISSUE THREAD

**Issue by joelvdavies** [ral-facilities/datagateway#940]
**Description**:
Some of the details panels repeat titles e.g. Name, Samples. Screenshot:
![image](https://user-images.githubusercontent.com/90245114/142891905-a26d8989-f47a-4ddb-ae18-23655d6886a7.png)

An example of the one with samples is the second result in https://datagateway.isis.stfc.ac.uk/browse/instrument/1/facilityCycle/3/investigation?view=card&sort=%7B%22startDate%22%3A%22desc%22%7D.

**Acceptance criteria**:
- [ ] Only one title present

**Comment by louise-davies** [comment]
TopCAT also has these repeated `Name` labels:

![image](https://user-images.githubusercontent.com/22525471/143416859-c5fe52aa-a710-45d7-a0bf-6a7fbfb1c0dc.png)

![image](https://user-images.githubusercontent.com/22525471/143416740-eb594bfc-b0bb-46dc-a4ae-9538513f59d4.png)

Just giving context that that's why we have the repeated labels, but we could probably just get away with a list of names
