### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/datagateway#954]
**Description**:

**This is a draft**

These are suggestions to improve the homepage:
- remove the large DataGateway logo (it is enough to have the logo in the banner at the top)
- add organisation logos at the bottom
- change the labels for buttons for the three functionality: browse, discover/search, download

**Acceptance criteria**:
- [ ] A checklist
- [ ] of criteria to accept this story as done

**Comment by mattjSTFC** [comment]
Some suggestions below for the homepage (appreciate I am not fully aware of the complexities of the DG project so may not be aware of any limitations or requirements):

**Top Nav**

- I would personally remove "Contact" and "Help" text links in the top nav bar and just lead with the help icon. Currently having Help and the help icon duplicate actions. The help icon link could take users to: https://datagateway.isis.stfc.ac.uk/help instead of showing the guide taking you through all the options. In the actual help page you can then promote the contact details within its own section.
- The key navigation page highlights shown when clicking on the help icon seem a little redundant as it doesn't offer much of value. However as a power user of the web I could be one sided with this. For example the bell icon for notifications is a well known decorative indication, "Sign In" is clear enough as text and doesn't need qualifying. Contact and help could be removed as above.
- The cog icon, for me, indicates "user" settings and my personal feeling is that it shouldn't be used for cookies. Cookie information could go in the footer (which is where I would expect it to be)
- This would need more investigation but I wonder for light / dark themes it might be better to show whether it is on or off. At the moment it states a "toggle" but doesn't show whether dark or light is set. Maybe a switch would help but also aware that this isn't a perfect solution
- Should the notification icon only show once you are signed in? Unless I am missing something with the platform? I do at times see a user session error but find this unhelpful

**Side bar**

- After saying no to this I think it would be better if the side bar links were visible as default. There doesn't seem to be a reason for having them hidden. Having them shown can only help aid users in understanding what options are available to them. If screen real estate is a priority then maybe allow users the option to minimise this panel but keep visible as default.
- If the sidebar were to remain visible I would remove the DG logo from the top of the panel as the logo only needs to be on the page once. Currently the logo can appear three times (top nav, side bar and hero banner). Appreciate that the top nav and side bar would need some re-work to position the logo and chevron accordingly if this was greed.
- I would also consider changing the left hand links to: Browse (heading), Data, Studies, My data. This way it then reads "Browse Data", "Browse Studies" and so on. Data Discover & access aren't quite as clear cut. It would be good to understand more about the navigation links in general to see if the second section can be improved. Are My Data and Download 
 personalised areas of the platform? If so maybe these should be grouped. Could you have a section called My DataGateway (heading) followed by Data and Downloads so it reads "My DataGateway Data" and "My DataGateway Downloads". What happens with Search though? Maybe this moves to the first section of links.
- I think this has been mention before but is "Download" the right nav link text for this section? But this might not be an issue with the above comment

***Main content***

- The 3 circular images feel disconnected from the textual content. Explore has a cityscape but talks about data produced at the facility. Discover refers to Data but shows code. Download maybe is the one image that could make sense

***Footer***

- The footer links take you to ISIS pages and two of the links, privacy and about us, felt odd moving away from the platform. Can the info be added to DG? So it becomes DG privacy and DG about us
- Also why is ISIS Home added to the footer? What does ISIS have to do with DataGateway? ok I am being silly here but to a user that doesn't have the background there is no information connecting DG and ISIS on the main page.

**Comment by louise-davies** [comment]
Matt & I had a discussion about these points and the UXPin mockup:
- the UXPin mockup looks really good and I agree that we should change the homepage to look like that
- I agree with the initially open sidebar - we might as well make it minimisable since the functionality is already there
- We agreed with removing the `Contact` page - and moving this into the footer and rather than making it a separate webpage instead just having a `mailto:` link
- I agree we should probably evaluate which help tour steps are necessary as some are pretty redundant - however we as web developers are bias in that we know what all these things are and therefore don't need help but we can't always assume users are the same
- Removing the unnecessary logos also seems sensible
- Again. I agree we should reevaluate the navigation order/text but what we should change them to/how we should group them is unknown
- Agree that it would be good to change the theme toggles to indicate which is currently selected by changing the text i.e. switch to darkmode, turn on high contrast mode etc.

TBD:
- How to represent both the help page and the help tour as both are useful and are wanted?

Various things like the footer links navigating away, explaining the reasoning for cookie management under the settings icon were discussed and if not mentioned above were agreed to leave as is.

**Comment by mattjSTFC** [comment]
I noticed the following on Behance, within the footer section, which conveys better my comment about cookies in the settings menu options. This was what I was thinking:

![image](https://user-images.githubusercontent.com/56403718/144209904-c0596953-4282-4d21-926f-070531ac1a76.png)

It really is minor in the grand scheme of things but to me this feels like a more intuitive place to look if you are one of the very few people that are concerned about what cookies are being set. 

My feeling is that users visiting DataGateway will more than likely accept the cookie nudge when visiting for the first time and then more than likely never revisit what has been set. Again based on my own experiences, which may be one sided, but I always accept a cookie prompt and then never go back to manage the preferences. 

Just some food for thought. 

One other thing re the cookie nudge. It might be worth updating the green colour to meet the UKRI / STFC branding:

![image](https://user-images.githubusercontent.com/56403718/144214970-4ec9db31-7250-4dd0-b6ee-1f55d4cba7d2.png)

**Comment by joelvdavies** [comment]
I agree with the latest comments from Louise, although I do see the point about the cookies link. Many websites have links in the footer but then I am unsure about the current reasoning.

As for colour changes I agree we should make them match UKRI/STFC branding as much as possible - the main limiting factor is meeting accessibility requirements for contrast. I just checked the green used and it is defined in the UKRI branding, although there is a lighter variant which seems to be more common - this would require using black text instead.
![image](https://user-images.githubusercontent.com/90245114/144222213-3917e3f8-a8e1-4c5b-8ee8-48e91950e48d.png)

**Comment by mattjSTFC** [comment]
Thanks @joelvdavies. If there is agreement to align then I would be hesitant to use any green, especially within a prominent feature, as it's not recommended in the UKRI colour guidance:

![image](https://user-images.githubusercontent.com/56403718/144225503-59706b53-bfa0-4046-bbbe-fb2aefa610e3.png)

"The Bright colour directly opposite the lead colour (or either of the Bright colours adjacent to it) is used as the accent colour."

"These are the primary colour palettes for each council."

![image](https://user-images.githubusercontent.com/56403718/144226117-456485cb-5313-4065-97ce-a8124f669500.png)

However I appreciate using a green colour is always useful for successes or confirmations that result in a positive outcome but these could be used in a subtle way. For example green tick icon or a chip / pill component.

**Comment by louise-davies** [comment]
Linking the UXPIN mockup: https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/144657834/simulate/no-panels
