### ISSUE TITLE
Ensure homepage uses RouterLinks

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/datagateway#988]
**Description**:
Currently, clicking on one of the homepage links causes a page reload. This is because it's not using the `Link` component from `react-router`. This should be corrected (perhaps in the new homepage only?) as this causes the navigation to be more efficient (we don't need to reload settings etc.)

**Acceptance criteria**:
- [ ] Clicking on a homepage link navigates internally via `react-router`

**Comment by louise-davies** [comment]
Additionally, this issue also occurs in the search help component & the search examples - could this also be fixed?

**Comment by joelvdavies** [comment]
@louise-davies The ones below the search box certainly can, the ones in the help text are a bit more difficult as currently they will not work unless the page actually reloads.

**Comment by joelvdavies** [comment]
@louise-davies Had a look into it and tried a few different methods. Not sure there is a very nice solution since 'useLuceneSearch' needs to be redefined with the new search text in order to work. This currently needs a re-render to happen but then automatically initiating the search on the re-render seems to be challenge. Using a new state for example just interrupts the search so that nothing will happen.

**Comment by louise-davies** [comment]
@joelvdavies hmmm, maybe it's a future consideration then.
